export const defaultStoreProductFields = [
  'id',
  'title',
  'handle',
  'subtitle',
  'description',
  'thumbnail',
  'images.id',
  'images.url',
  'collection.id',
  'collection.title',
  'collection.handle',
  'type.id',
  'type.value',
  'options.id',
  'options.title',
  'options.values.id',
  'options.values.value',
  'options.values.option_id',
  'categories.id',
  'categories.name',
  'categories.handle',
  'categories.parent_category_id',
  'variants.id',
  'variants.title',
  'variants.variant_rank',
  'variants.sku',
  'variants.options.id',
  'variants.options.option_id',
  'variants.options.value',
  'vehicle_model.*',
  'vehicle_model.make.id',
  'vehicle_model.make.name',
  'vehicle_model_link.*',
  'variants.vehicle_trim.id',
  'variants.vehicle_trim.title',
  'variants.vehicle_trim.sort_rank',
  'variants.vehicle_trim_link.mileage',
  'variants.vehicle_trim_link.year',
  'variants.calculated_price.*',
  'variants.manage_inventory',
  'variants.calculated_price',
];

export const retrieveProductQueryConfig = {
  defaults: defaultStoreProductFields,
  isList: false,
};

export const listProductQueryConfig = {
  ...retrieveProductQueryConfig,
  defaultLimit: 50,
  isList: true,
};
